controller_list:
  - name: fake_manipulator_controller
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
  - name: fake_eff_controller
    joints:
      - left_grip_joint
      - right_grip_joint